### ISSUE TITLE
When I execute rope.stop (true), it will triggered onAnimationEnd

### ISSUE THREAD

**Issue by sweet2o09** [daimajia/AndroidViewAnimations#100]
When I execute rope.stop (true), it will trigger onAnimationEnd

code:
`rope2 = YoYo.with(...).onEnd(new YoYo.AnimatorCallback() {
                        @Override
                        public void call(Animator animator) {
                            if (rope != null) {
                                rope.stop(true);
                            }
                        }
                    })
                    .playOn(mV2WLoginCurrentCountA);`
ERROR:
FATAL EXCEPTION: main
 java.lang.StackOverflowError: stack size 8MB
                                                                             at com.daimajia.androidanimations.library.YoYo$1.onAnimationCancel(YoYo.java:295)
                                                                             at android.animation.AnimatorSet.cancel(AnimatorSet.java:327)
                                                                             at com.daimajia.androidanimations.library.BaseViewAnimator.cancel(BaseViewAnimator.java:108)
                                                                             at com.daimajia.androidanimations.library.YoYo$YoYoString.stop(YoYo.java:240)

**Comment by sweet2o09** [comment]
compile 'com.daimajia.easing:library:2.0@aar'
compile 'com.daimajia.androidanimations:library:2.2@aar'
