### ISSUE TITLE
java.lang.Error: Can not init easingMethod instance

### ISSUE THREAD

**Issue by iman2420** [daimajia/AndroidViewAnimations#112]
**I got java.lang.Error after sign apk:**
`? E/UncaughtException: java.lang.Error: Can not init easingMethod instance
                           at com.daimajia.a.c.a(Unknown Source)
                           at com.daimajia.a.b.a(Unknown Source)
                           at com.daimajia.a.b.a(Unknown Source)
                           at com.daimajia.androidanimations.library.specials.out.TakingOffAnimator.prepare(Unknown Source)
                           at com.daimajia.androidanimations.library.BaseViewAnimator.setTarget(Unknown Source)
                           at com.daimajia.androidanimations.library.YoYo.play(Unknown Source)
                           at com.daimajia.androidanimations.library.YoYo.access$1400(Unknown Source)
                           at com.daimajia.androidanimations.library.YoYo$AnimationComposer.playOn(Unknown Source)
                           at com.android.quiz.PeopleDetailActivity.c(Unknown Source)
                           at com.android.quiz.PeopleDetailActivity$getWalldetails$1.a(Unknown Source)
                           at com.android.quiz.PeopleDetailActivity$getWalldetails$1.a(Unknown Source)
                           at com.android.volley.toolbox.StringRequest.c(Unknown Source)
                           at com.android.volley.toolbox.StringRequest.b(Unknown Source)
                           at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(Unknown Source)
                           at android.os.Handler.handleCallback(Handler.java:743)
                           at android.os.Handler.dispatchMessage(Handler.java:95)
                           at android.os.Looper.loop(Looper.java:150)
                           at android.app.ActivityThread.main(ActivityThread.java:5621)
                           at java.lang.reflect.Method.invoke(Native Method)
                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)`
**And this is my proguard file:**

    `-keepnames class com.daimajia.androidanimations.**
    -keepnames class com.daimajia.library.**
    -keep class com.daimajia.androidanimations.** { *; }
    -keep class com.daimajia.library.** { *; }
    -dontwarn com.daimajia.**`

**Comment by iman2420** [comment]
I solve this problem by change to:

          `-keep class com.daimajia.** { *; }
           -dontwarn com.daimajia.**
           -keepnames class com.daimajia.**`
