### ISSUE TITLE
android 4.4动效好像不兼容

### ISSUE THREAD

**Issue by sweet2o09** [daimajia/AndroidViewAnimations#97]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.jfkd.additionpocket, PID: 13560
                                                                         java.lang.NullPointerException
                                                                             at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:797)
                                                                             at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
                                                                             at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
                                                                             at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
                                                                             at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
                                                                             at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
                                                                             at android.view.Choreographer.doCallbacks(Choreographer.java:603)
                                                                             at android.view.Choreographer.doFrame(Choreographer.java:571)
                                                                             at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
                                                                             at android.os.Handler.handleCallback(Handler.java:808)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                             at android.os.Looper.loop(Looper.java:193)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5528)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
                                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by daimajia** [comment]
Please use English for considering the foreigner developers. This issue is duplicate with #91 .
